[package]
name = "rust-architecture"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
argh = "0.1"
glob = "0.3"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.9"
